name: Tests
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
